<?php
/**
 * Amx system.php configuration file.
 * Do not edit this file !
 */

if (!defined('BASEPATH'))
    exit('No direct script access allowed');


$config['load_custom_js'] = TRUE;


/**
 * Amx services table structure
 */
$config['amx_table_structure'] = array(
    'id' => array('type' => 'INT', 'auto_increment' => TRUE),
    'server_id' => array('type' => 'INT', 'constraint' => '11'),
    'username' => array('type' => 'VARCHAR', 'constraint' => '64'),
    'expires' => array('type' => 'VARCHAR', 'constraint' => '12'),
    'module' => array('type' => 'VARCHAR', 'constraint' => '12'),
    'service' => array('type' => 'VARCHAR', 'constraint' => '12'),
);


$config['submenu_names'] = array(
    'unban' => 'Lietotāju banu saraksts',
    'nickname' => 'Reģistrēto saraksts',
    'slot' => 'Slot lietotāji',
    'access' => 'AMX access lietotāji',
    'vip' => 'VIP lietotāji',
    'accessvip' => 'AMX access + VIP lietotāji',
    
);


/**
 * Controlls which service needs obligatory login into system and other services settings
 */
$config['services_settings'] = array(
    
    'unban' => array(
        'login_required' => FALSE,
        'type' => 'one-time',
    ),
    
    'nickname' => array(
        'login_required' => FALSE,
        'type' => 'subscription',
    ),
    
    'slot' => array(
        'login_required' => FALSE,
        'type' => 'subscription',
    ),
    
    'access' => array(
        'login_required' => FALSE,
        'type' => 'subscription',
    ),
    
    'vip' => array(
        'login_required' => FALSE,
        'type' => 'subscription',
    ),
    
    'accessvip' => array(
        'login_required' => FALSE,
        'type' => 'subscription',
    ),
 
);


$config['fields_unban'] = array(
    
    'ipaddress' => array(
        'label' => 'Tava IP adrese',
        'type' => 'input',
        'fill' => 'mandatory',
        'wizard_step' => 1,
        'ajax_validation' => 'required valid_ip check_banned_ip',
        'php_validation' => 'required|xss_clean|max_length[15]|min_length[7]|valid_ip|callback__amx_check_banned_ip',
        'options' => array(
            'name' => 'ipaddress',
            'id' => 'ipaddress',
            'value' => set_value('ipaddress'),
            'maxlength' => '15',
            'minlength' => '7',
        ),
    ),
    
);


$config['fields_amx'] = array(
  
    'servers' => array(
        'label' => 'Izvēlies serveri',
        'type' => 'dropdown',
        'fill' => 'mandatory',
        'wizard_step' => 2,
        'php_validation' => 'xss_clean',
        'options' => 'autocomplete="off" id="servers" class="chosen"',
        'value' => set_value('servers'),
    ),    
    
    'username' => array(
        'label' => 'Tavs lietotājvārds',
        'type' => 'input',
        'fill' => 'mandatory',
        'wizard_step' => 1,
        'ajax_validation' => 'required check_user',
        'php_validation' => 'required|xss_clean|max_length[30]|min_length[2]',
        'options' => array(
            'name' => 'username',
            'id' => 'username',
            'value' => set_value('username'),
            'maxlength' => '30',
            'minlength' => '2',
        ),
    ),
    
    'password' => array(
        'label' => 'Tava parole',
        'type' => 'input',
        'fill' => 'mandatory',
        'wizard_step' => 1,
        'ajax_validation' => 'required',
        'php_validation' => 'required|xss_clean|max_length[32]|min_length[2]',
        'options' => array(
            'name' => 'password',
            'id' => 'password',
            'value' => set_value('password'),
            'maxlength' => '32',
            'minlength' => '2',
        ),
    ),
    
);