<?php
/**
 * General system.php configuration file.
 * Do not edit this file !
 */

if (!defined('BASEPATH'))
    exit('No direct script access allowed');


$config['load_custom_js'] = TRUE;


/**
 * Donate services table structure
 */ 
$config['donate_table_structure'] = array(
    'id' => array('type' => 'INT', 'auto_increment' => TRUE),
    'user_id' => array('type' => 'INT', 'constraint' => '11'),
    'username' => array('type' => 'VARCHAR', 'constraint' => '64'),
    'message' => array('type' => 'VARCHAR', 'constraint' => '255'),
    
    'sms_money' => array('type' => 'DECIMAL', 'constraint' => '5,2'),
    'ibank_money' => array('type' => 'DECIMAL', 'constraint' => '5,2'),
    'paypal_money' => array('type' => 'DECIMAL', 'constraint' => '5,2'),
    'total' => array('type' => 'DECIMAL', 'constraint' => '5,2'),
    
    'datetime' => array('type' => 'VARCHAR', 'constraint' => '12'),
);


$config['submenu_names'] = array(
    'donate' => 'Atbalstītāju saraksts'
);


/**
 * Controlls which service needs obligatory login into system
 */
$config['services_settings'] = array(
    
    'donate' => array(
        'login_required' => FALSE,
    ),

);


/**
 * Fields for general services
 */
$config['fields_donate'] = array(
    
    'username' => array(
        'label' => 'Tavs vārds',
        'type' => 'input',
        'fill' => 'mandatory',
        'wizard_step' => 1,
        'ajax_validation' => 'required',
        'php_validation' => 'required|xss_clean|max_length[50]|min_length[2]',
        'options' => array(
            'name' => 'username',
            'id' => 'username',
            'value' => set_value('username'),
            'maxlength' => '30',
            'minlength' => '2',
        ),
    ),
    
    'message' => array(
        'label' => 'Tava ziņa',
        'type' => 'input',
        'fill' => 'mandatory',
        'wizard_step' => 1,
        'ajax_validation' => '',
        'php_validation' => 'xss_clean|max_length[160]|min_length[2]',
        'options' => array(
            'name' => 'message',
            'id' => 'message',
            'value' => set_value('message'),
            'maxlength' => '160',
            'minlength' => '2',
        ),
    ),
    
);
